# Generated by Django 4.0 on 2022-01-27 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LiquidGold', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieselrequests',
            name='cto_status',
            field=models.CharField(choices=[('Approved', 'approved'), ('Rejected', 'rejected'), ('Pending', 'pending'), ('Confirmed', 'confirmed')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='dieselrequests',
            name='engineer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='LiquidGold.engineer', verbose_name='Confirm Engineer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dieselrequests',
            name='justification',
            field=models.CharField(default=2, max_length=3000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dieselrequests',
            name='noc_status',
            field=models.CharField(choices=[('Approved', 'approved'), ('Rejected', 'rejected'), ('Pending', 'pending'), ('Confirmed', 'confirmed')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='dieselrequests',
            name='phcn_comment',
            field=models.CharField(default=4, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dieselrequests',
            name='quantity_required',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dieselrequests',
            name='site',
            field=models.ForeignKey(default=256, on_delete=django.db.models.deletion.DO_NOTHING, to='LiquidGold.site', verbose_name='Confirm Site'),
            preserve_default=False,
        ),
    ]
