# Generated by Django 4.0 on 2022-02-02 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LiquidGold', '0004_alter_dieselrequests_manager_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieselrequests',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LiquidGold.engineer', verbose_name='Confirm Engineer'),
        ),
        migrations.AlterField(
            model_name='dieselrequests',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LiquidGold.site', verbose_name='Confirm Site'),
        ),
    ]
